name: $(Build.DefinitionName)_$(Date:yyyyMMdd))

trigger:
- master

queue:
  name: Hosted VS2017

steps:
- powershell: .\bootstrap.ps1
  displayName: 'Install pre-requisites'
  
- powershell: Invoke-Build -Configuration 'Production' -Task Clean, UpdateHelp, UpdateVersion, CopyModuleFiles, PublishModule
  displayName: 'Publish PowerShell Module'
  env:
    psgallery: $(NugetAPIKey)